spring.application.name=p3project

#POSTGRES ENV
spring.datasource.url=jdbc:postgresql://localhost:5432/expensemanager
spring.datasource.username=postgres
spring.datasource.password=postgres
#spring.sql.init.mode=always

#JWT ENV
jwt.secret=my_very_long_secret_key_that_is_at_least_32_characters_long_for_security
jwt.expiration=86400000



