spring.application.name=p3project
spring.datasource.url=jdbc:postgresql://localhost:5432/expensemanager
spring.datasource.username=postgres
spring.datasource.password=postgres

#spring.sql.init.mode=always

